#pragma once

#define VG_VERSION_MAJOR 1
#define VG_VERSION_MINOR 0
#define VG_VERSION_PATCH 0

#define STRINGIFY2(STR) #STR
#define STRINGIFY(STR) STRINGIFY2(STR)

#define VG_STR_VERSION \
	STRINGIFY(VG_VERSION_MAJOR) "." \
	STRINGIFY(VG_VERSION_MINOR) "." \
	STRINGIFY(VG_VERSION_PATCH)
